### ISSUE TITLE
Drop requirement Python < 3.9?

### ISSUE THREAD

**Issue by bilke** [oemof/tespy#252]
Hi @fwitte,

is the [requirement](https://github.com/oemof/tespy/blob/dev/setup.py#L65) that Python is `< 3.9` really needed? I mean does it really not work under 3.9 or is it simply not tested on 3.9?

If the later is the case then I would be very happy if you would drop the requirement!

**Comment by fwitte** [comment]
Hi @bilke,
thank you for the hint. I will look into it on Monday next week. Originally, I remember that there was some trouble with CoolProp and Python 3.9 (https://github.com/CoolProp/CoolProp/issues/1981). I did not yet recheck, I'll let you know once I did.
Best regards and have a nice weekend

**Comment by fwitte** [comment]
Hi again,
I tried it on my locally in a fresh 3.9 environment, and the issue I keep having is, that the automatic installation of CoolProp when trying to install with pip just fails as reported in the CoolProp issue (python 3.9 wrapper not yet available) linked in my first reply. The same issue occurs with installation through the CI (https://github.com/oemof/tespy/pull/253/checks?check_run_id=2182694832). Honestly, I prefer to wait until the python 3.9 wrapper is released to avoid confusion for less experienced users when installing from pypi on an environment with python 3.9 installed (instead of a kind of cyrptic error message, they get a clear message, that python 3.9 is not supported).
Best regards
Francesco

**Comment by bilke** [comment]
Thanks for the investigation! I am perfectly fine with waiting for the 3.9 support in CoolProp!

**Comment by bilke** [comment]
FYI: Looks like CoolProp recently added support for newer Pythons: https://github.com/CoolProp/CoolProp/pull/2097. Although they did not yet release a new version because they want to get some feedback: https://github.com/CoolProp/CoolProp/issues/2119.

**Comment by ChaofanChen** [comment]
Hi everyone,

I am wondering, does TESPy still have the requirement of python version < 3.9? 

Best,
Chaofan

**Comment by fwitte** [comment]
I tested installation of CoolProp with Pyton 3.9 and 3.10 on windows using conda and on ubuntu. Seems to work, is already integrated in dev and will be in the next release soon. Closing this then!
